- name: install nginx server
  hosts: frontend
  become: yes
  tasks:
    - name: install nginx 
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start and enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes