- name: play level varaibles
  hosts: local
  connection: local
  vars:
    COURSE: ansible  # course=ansible in shell
    DURATION: 10H
    TRAINER: SIVAKUMAR
  tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is : {{ TRAINER }}"

    - name: print course information
      vars:
        COURSE: AwsDevOps
        DURATION: 20H
      ansible.builtin.debug:
        msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is : {{ TRAINER }}"