- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: USERNAME
      prompt: enter the username
      private: false

    - name: PASSWORD
      prompt: enter your password
      private: true
  tasks:
    - name: print the user credentials
      ansible.builtin.debug:
        msg: "username : {{ USERNAME }} AND password : {{ PASSWORD }}"

