- name: varaibles from inventory
  hosts: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello, I am Learning {{ COURSE }}, Duration is: {{ DURATION }} and the trainer is: {{ TRAINER }}"