- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120 # this is number
    COURSE: DeSecOps with AWS # this is string
    IS_LIVE: true # boolean
    TOOLS:   # []
    - Linux
    - shell
    - Ansible
    CONCEPTS:   # {}
      CI: Jenkins
      SCRIPTING: "shell, Ansible, Terraform, Python"
  tasks:
  - name: print course information
  ansible.builtin.debug:
    msg: "Course is: {{ COURSE }}, Duration is {{ DURATION }}, IS_LIVE? :{{ IS_LIVE }}, Tools are: {{ TOOLS }}, Concepts are: {{ CONCEPTS }}"
