- name: loops
  hosts: local
  connection: local
  loop:   # In Ansible, loop is used inside a task— not at the play level.
  - nanda
  - siva
  - vinay
  - sam
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Helloo, {{ item }}"