- name: functions
  hosts: local
  connection: local
  vars:
    person: nanda, siva, kajal, sam
  tasks:
  - name: check undefined varaibles
    ansible.builtin.debug:
      msg: "hello, {{ person | default('Ramesh') }}"

  - name: split the string
    ansible.builtin.debug:
      msg: "hello, {{ person | split(',') }}"

  - name: map to list
    vars:
      course:
        name: aws DevOps
        duration: 11
        trainer: nanda
    ansible.builtin.debug:
      msg: "hello, {{ course | dict2items }}"

  - name: list to map
    vars:
      course:
      - {'key': 'name', 'value': 'aws DevOps'}
      - {'key': 'duration', 'value': 11}
      - {'key': 'trainer', 'value': 'nanda'}
    ansible.builtin.debug:
      msg: "hello, {{ course | items2dict }}"

  - name: covert string to upper
    vars:
    - name: NandaKumar
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: covert string to lower
    vars:
    - name: NandaKumar
    ansible.builtin.debug:
      msg: "{{ name | lower }}"

  - name: check IP Address is valid or not
    vars:
    - IP: "300.242.544.343"
    ansible.builtin.debug:
      msg: "{{ IP | ansible.utils.ipaddr }}"